In [1]:
import numpy as np
from copy import copy, deepcopy
from functools import reduce

In [2]:
A = [[-1,-7,-3,-2],
     [-8,1,-9,0],
     [8,2,-5,-3],
     [-5,3,5,-9]]

A = [[1,2],
     [3,4]]

b = [-12,-60,-91,-43]

## LUP разложение

In [3]:
def LUP_solution(A, B):
    A_ = deepcopy(A)
    B_ = B
    A_, P = LUP_decomposition(A_)
    X = LUP_solve(A_, P, B_)
    return X

def LUP_decomposition(A):
    A_ = deepcopy(A)
    size = len(A_)
    P = [i for i in range(size)]
    k_ = 0
    for k in range(size):
        flag = 0
        for i in range(k, size):
            if abs(A_[i][k]) > flag:
                flag = abs(A_[i][k])
                k_ = i
        if flag == 0:
            print('Вырожденная матрица\n')
            return -1    
        swap(P, k ,k_)
        swap(A_, k, k_)
        for i in range(k + 1, size):
            A_[i][k] = A_[i][k] / A_[k][k]
            for j in range(k + 1, size):
                A_[i][j] = A_[i][j] - A_[i][k] * A_[k][j]
    return A_, P

def swap(a, i, j):
    t = a[i]
    a[i] = a[j]
    a[j] = t

def LUP_solve(A, P, B):
    size = len(A)
    X = [0 for i in range(size)]
    Y = [0 for i in range(size)]
    for i in range(size):
        if i == 0:
            Y[i] = B[P[i]]
        else:
            suma_y = sum(map(lambda u, y: u * y, A[i][:i], Y[:i]))
            Y[i] = B[P[i]] - suma_y
    for i in range(size - 1, -1, -1):
        if i == size - 1:
            X[i] = Y[i] / A[i][i]
        else:
            suma_x = sum(map(lambda l, x: l * x, A[i][i + 1 :], X[i + 1 :]))
            X[i] = (Y[i] - suma_x) / A[i][i]
    return X

In [7]:
a,b = LUP_decomposition(A)
a

[[-8, 1, -9, 0],
 [0.125, -7.125, -1.875, -2.0],
 [-1.0, -0.42105263157894735, -14.789473684210526, -3.8421052631578947],
 [0.625, -0.3333333333333333, -0.6761565836298933, -12.26453143534994]]

In [8]:
b

[1, 0, 2, 3]

In [6]:
LUP_solution(A, b)

[-2.0, -4.0, 8.0, 9.0]

In [5]:
np.linalg.solve(A, b)

array([-2., -4.,  8.,  9.])

## Обратная матрица

In [8]:
# inversing
def LUP_inverse(A):
    A_ = deepcopy(A)
    E = [[1 if i == j else 0 for i in range (len(A))] for j in range(len(A))]
    inv =[]
    for i in range(len(E)):
        column = get_column(E, i)
        column = column_to_vec(column)
        inv.append(LUP_solution(A_, column))
    inv = transpose(inv)
    return inv

def get_column(A, k):
    column = [[0] for i in range(len(A))]
    for i in range(len(A)):
        column[i][0] = A[i][k]
    return column

def column_to_vec(column):
    vec = []
    for i in range (len(column)):
        vec.append(column[i][0])
    return vec

def transpose(A):
    C = [[A[j][i] for j in range(len(A))]
    for i in range(len(A[0]))]
    return  C

In [9]:
np.array(LUP_inverse(A))

array([[ 0.00203114, -0.04807041,  0.06364252, -0.02166554],
       [-0.12215882,  0.03394912,  0.02949995,  0.01731309],
       [-0.01537866, -0.06460973, -0.05329336,  0.02118193],
       [-0.05039172,  0.00212787, -0.05513106, -0.08153593]])

In [10]:
np.linalg.inv(np.array(A))

array([[ 0.00203114, -0.04807041,  0.06364252, -0.02166554],
       [-0.12215882,  0.03394912,  0.02949995,  0.01731309],
       [-0.01537866, -0.06460973, -0.05329336,  0.02118193],
       [-0.05039172,  0.00212787, -0.05513106, -0.08153593]])

## Детерминант

In [11]:
# determinant
def LUP_determinant(A):
    A_ = deepcopy(A)
    A_ = LUP_decomposition(A_)[0]
    return reduce(lambda x, y: x * y, [A_[i][i] for i in range(len(A_))])

In [47]:
-LUP_determinant(A)

-10339.0

In [48]:
np.linalg.det(A)

-10338.999999999996