In [3]:
import numpy as np

In [4]:
A = [[-14,-6],[-9,15,-1],[1,-11,1],[-7,12,3],[6,-7]]
b = [-78,-73,-38,77,91]

## Метод прогонки

In [5]:
def solve(m, b):
    y = [None] * len(m)
    alpha = [None] * len(m)
    beta = [None] * len(m)
    for i in range(len(m)):
        if i == 0:
            y[i] = m[i][0]
            alpha[i] = -1 * m[i][1] / y[i]
            beta[i] = b[i] / y[i]
        elif i == len(m) - 1:
            y[i] = m[i][1] + m[i][0] * alpha[i-1]
            beta[i] = (b[i] - m[i][0] * beta[i-1]) / y[i]
        else:
            y[i] = m[i][1] + m[i][0] * alpha[i-1]
            alpha[i] = -1 * m[i][2] / y[i]
            beta[i] = (b[i] - m[i][0] * beta[i-1]) / y[i]
    x = [0] * len(m)
    for i in range(len(m)):
        if i == 0:
            x[len(m)-i-1] = beta[len(m)-i-1]
        else:
            x[len(m)-i-1] = alpha[len(m)-i-1] * x[len(m)-i] + beta[len(m)-i-1]
    return x

## x vector

In [6]:
x = solve(A,b)

In [7]:
np.array(x)

array([ 5.99374122, -0.98539618,  4.27538638, 10.0146464 , -4.41601737])

## trig matrix

In [8]:
def make_trig_matrix(A):
    m = []
    for i in range(len(A)):
        m.append([0]*len(A))
    for i in range(len(A)):
        if i == 0:
            m[i][0] = A[i][0]
            m[i][1] = A[i][1]
        elif i == len(A)-1:
            m[i][i-1] = A[i][0]
            m[i][i] = A[i][1]
        else:
            m[i][i-1] = A[i][0]
            m[i][i] = A[i][1]
            m[i][i+1] = A[i][2]
    return m

In [9]:
np.array(make_trig_matrix(A))

array([[-14,  -6,   0,   0,   0],
       [ -9,  15,  -1,   0,   0],
       [  0,   1, -11,   1,   0],
       [  0,   0,  -7,  12,   3],
       [  0,   0,   0,   6,  -7]])

## b vector

In [10]:
np.array(b)

array([-78, -73, -38,  77,  91])

## prove for x

In [ ]:
def prove(A, x):
    n = len(A)
    res = [0] * n
    for i in range(n):
        for j in range(n):
            res[i] += A[i][j] * x[j]
    return res

In [ ]:
prove(make_trig_matrix(A),x)

[-77.99999999999999, -73.0, -38.0, 77.0, 91.0]