### Лабораторная работа №1 по курсу Математическая экономика

Работу выполнил Гамов Павел м80-407б-18

In [1]:
import gurobipy as gp
from gurobipy import GRB
import numpy as np

In [2]:
k = 4
l = 7
n = 10 + k//4
m = 30 - k//4

In [3]:
B = np.zeros((m))
for i in range(m):
    B[i] = 70+l+k+i
B

array([ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,
        92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101., 102.,
       103., 104., 105., 106., 107., 108., 109.])

In [4]:
C = np.zeros((n))
for i in range(n):
    C[i] = 50+l+k-i
C

array([61., 60., 59., 58., 57., 56., 55., 54., 53., 52., 51.])

In [5]:
A = np.zeros((m,n))
x = k//5
for i in range(m):  
    for j in range(n):
        A[i] = 1+((j+k)*i+j*j+i*i*i+3*(i+l)) % (30+x)
A

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2

Создаем модель для оптимизации целевой функции и запускаем её

In [6]:
# Declare and initialize model
m1 = gp.Model('RAP')
x = m1.addMVar(shape=11, vtype=GRB.BINARY, name="x")
m1.setObjective(C @ x, GRB.MAXIMIZE)
m1.addConstr(A @ x <= B, name="c")
m1.optimize()

Restricted license - for non-production use only - expires 2023-10-25
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 4 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 29 rows, 11 columns and 319 nonzeros
Model fingerprint: 0xc57f475b
Variable types: 0 continuous, 11 integer (11 binary)
Coefficient statistics:
  Matrix range     [2e+00, 2e+01]
  Objective range  [5e+01, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [8e+01, 1e+02]
Found heuristic solution: objective 238.0000000
Presolve removed 29 rows and 11 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 4 available processors)

Solution count 1: 238 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.380000000000e+02, best bound 2.380000000000e+02, gap 0.0000%


In [7]:
 print(x.X)

[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
print('Obj: %g' % m1.ObjVal)

Obj: 238


Создаем модель для оптимизации двойственной задачи и запускаем её

In [9]:
m2 = gp.Model('RAP2')
y = m2.addMVar(shape=13, vtype=GRB.BINARY, name="y")
m2.setObjective(C @ x, GRB.MINIMIZE)
m2.addConstr(A @ x <= B, name="c")
m2.optimize()

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 4 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 29 rows, 13 columns and 319 nonzeros
Model fingerprint: 0xe566cfe7
Variable types: 0 continuous, 13 integer (13 binary)
Coefficient statistics:
  Matrix range     [2e+00, 2e+01]
  Objective range  [5e+01, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [8e+01, 1e+02]
Found heuristic solution: objective 0.0000000

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 4 available processors)

Solution count 1: 0 

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0000%


In [10]:
 print(y.X)

[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]


In [11]:
print('Obj: %g' % m2.ObjVal)

Obj: 0



Увеличим на 1 ресурс, который позволяет локально максимизировать значение целевой функции. Найдем новое решение.

In [12]:
for i in range(m):
    B[i] = 70+l+k+i

In [13]:
B[6] += 1
m3 = gp.Model('RAP')
x = m3.addMVar(shape=11, vtype=GRB.BINARY, name="x")
m3.setObjective(C @ x, GRB.MAXIMIZE)
m3.addConstr(A @ x <= B, name="c")
m3.optimize()

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 4 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 29 rows, 11 columns and 319 nonzeros
Model fingerprint: 0x6e54cd16
Variable types: 0 continuous, 11 integer (11 binary)
Coefficient statistics:
  Matrix range     [2e+00, 2e+01]
  Objective range  [5e+01, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [8e+01, 1e+02]
Found heuristic solution: objective 238.0000000
Presolve removed 29 rows and 11 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 4 available processors)

Solution count 1: 238 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.380000000000e+02, best bound 2.380000000000e+02, gap 0.0000%


In [14]:
 print(x.X)

[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
print('Obj: %g' % m3.ObjVal)

Obj: 238
